baseurl      = "https://luizm.dev"
title        = "LuizMuller"
languageCode = "en-us"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "SRE Engineer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Luiz Muller personal homepage"
  keywords = "blog,sre,devops,developer"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/luizm"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/luiz-antonio-muller-24165a14"

  [[params.social]]
    name = "email"
    url  = "mailto:contact@luiz.dev"

[taxonomies]
    category = "blog"


[languages]
  [languages.en]
    title = "Luiz Muller"
    copyright = ""

    [languages.en.params.logo]
      logoText = "whoami"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
